<a href="https://colab.research.google.com/github/Meisz00/googlecolab/blob/main/Big_Data_NB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_excel('Data Depresi Kelompok 5.xlsx', sheet_name = 'Data Filter Numerik')
df

school_year  age  gender  phq_score  suicidal  anxiety_diagnosis  \
0              1   19       0          9         0                  0   
1              1   18       0          8         0                  0   
2              1   19       0          8         0                  0   
3              1   18       1         19         1                  0   
4              1   18       0          6         0                  0   
..           ...  ...     ...        ...       ...                ...   
195            4   22       1          7         0                  0   
196            4   21       1          5         0                  0   
197            4   21       0         11         0                  0   
198            4   22       1          5         0                  0   
199            4   22       1          7         0                  1   

     sleepiness  depression_diagnosis  
0             0                     0  
1             1                     0  
2             0                     0  
3             1                     0  
4             0                     0  
..          ...                   ...  
195           0                     0  
196           0                     0  
197           0                     0  
198           0                     0  
199           1                     1  

[200 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   school_year           200 non-null    int64
 1   age                   200 non-null    int64
 2   gender                200 non-null    int64
 3   phq_score             200 non-null    int64
 4   suicidal              200 non-null    int64
 5   anxiety_diagnosis     200 non-null    int64
 6   sleepiness            200 non-null    int64
 7   depression_diagnosis  200 non-null    int64
dtypes: int64(8)
memory usage: 12.6 KB


In [ ]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [ ]:
x

array([[ 1, 19,  0, ...,  0,  0,  0],
       [ 1, 18,  0, ...,  0,  0,  1],
       [ 1, 19,  0, ...,  0,  0,  0],
       ...,
       [ 4, 21,  0, ...,  0,  0,  0],
       [ 4, 22,  1, ...,  0,  0,  0],
       [ 4, 22,  1, ...,  0,  1,  1]])

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1])

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=123)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((160, 7), (40, 7), (160,), (40,))

In [ ]:
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
classifier.predict_proba(x_test)

array([[9.16725872e-01, 8.32741284e-02],
       [9.98335969e-01, 1.66403143e-03],
       [9.99460939e-01, 5.39060808e-04],
       [9.97294390e-01, 2.70561000e-03],
       [9.99591930e-01, 4.08069673e-04],
       [9.87892622e-01, 1.21073778e-02],
       [9.89974699e-01, 1.00253012e-02],
       [9.94085620e-01, 5.91438044e-03],
       [9.76293699e-01, 2.37063010e-02],
       [9.54292245e-01, 4.57077545e-02],
       [9.89972577e-01, 1.00274226e-02],
       [9.88859082e-01, 1.11409175e-02],
       [9.70026693e-01, 2.99733071e-02],
       [9.62173649e-01, 3.78263505e-02],
       [9.13492437e-04, 9.99086508e-01],
       [9.99774311e-01, 2.25689331e-04],
       [9.99705738e-01, 2.94262368e-04],
       [9.97086899e-01, 2.91310058e-03],
       [5.00653888e-04, 9.99499346e-01],
       [9.99755126e-01, 2.44874318e-04],
       [2.11880428e-04, 9.99788120e-01],
       [9.99120424e-01, 8.79576286e-04],
       [9.62340505e-01, 3.76594949e-02],
       [9.97214244e-01, 2.78575598e-03],
       [9.978753

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[35  1]
 [ 1  3]]


In [ ]:
akurasi = classification_report(y_test, y_pred)
print(akurasi)

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        36
           1       0.75      0.75      0.75         4

    accuracy                           0.95        40
   macro avg       0.86      0.86      0.86        40
weighted avg       0.95      0.95      0.95        40



In [ ]:
akurasi = accuracy_score(y_test, y_pred)
print("Tingkat akurasi : %d persen"%(akurasi*100))

Tingkat akurasi : 95 persen


In [ ]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)
ydata

y_test  y_pred
0        0       0
1        0       0
2        0       0
3        0       0
4        0       0
5        0       0
6        0       0
7        0       0
8        0       0
9        0       0
10       0       0
11       0       0
12       0       0
13       1       0
14       0       1
15       0       0
16       0       0
17       0       0
18       1       1
19       0       0
20       1       1
21       0       0
22       0       0
23       0       0
24       0       0
25       0       0
26       0       0
27       0       0
28       0       0
29       0       0
30       0       0
31       0       0
32       1       1
33       0       0
34       0       0
35       0       0
36       0       0
37       0       0
38       0       0
39       0       0

In [ ]:
ydata.to_excel("datapredNB.xlsx", index = False)

In [ ]:
# Contoh data baru untuk prediksi
data_baru = {
    'school_year': [1],
    'age': [19],
    'gender': [1],
    'phq_score': [12],
    'suicidal' : [0],
    'anxiety_diagnosis' : [1],
    'sleepiness' : [0]
}
df_baru = pd.DataFrame(data_baru)

# Membuat prediksi
prediksi = classifier.predict(df_baru)
print("Prediksi diagnosis depresi:", prediksi[0])

Prediksi diagnosis depresi: 1


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(
